import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

export const getPublicChallengeFn = createServerFn({ method: "POST" })
  .inputValidator((data: { code: string }) => data)
  .handler(async ({ data }) => {
    const s = await import("./challenges.server");
    return s.getPublicChallenge(data.code);
  });

export const submitPublicAttemptFn = createServerFn({ method: "POST" })
  .inputValidator(
    (data: {
      code: string;
      studentName: string;
      phone: string;
      answers: Record<string, number>;
      timeTakenSeconds?: number;
    }) => data,
  )
  .handler(async ({ data }) => {
    const s = await import("./challenges.server");
    return s.submitPublicAttempt(data);
  });

export const listAdminChallengesFn = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { assertStaff } = await import("./admin.server");
    await assertStaff(context.supabase, context.userId);
    const s = await import("./challenges.server");
    return s.listAdminChallenges();
  });

export const createChallengeFn = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator(
    (data: {
      chapterId: string;
      title?: string;
      code?: string;
      questionCount?: number;
    }) => data,
  )
  .handler(async ({ data, context }) => {
    const { assertStaff } = await import("./admin.server");
    await assertStaff(context.supabase, context.userId);
    const s = await import("./challenges.server");
    return s.createChallenge(data);
  });

export const autoGenerateDailyChallengeFn = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { assertStaff } = await import("./admin.server");
    await assertStaff(context.supabase, context.userId);
    const s = await import("./challenges.server");
    return s.autoGenerateDailyChallenge();
  });

export const getChallengeLeadsFn = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data?: { challengeId?: string }) => data)
  .handler(async ({ data, context }) => {
    const { assertStaff } = await import("./admin.server");
    await assertStaff(context.supabase, context.userId);
    const s = await import("./challenges.server");
    return s.getChallengeLeads(data?.challengeId);
  });
