import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { 
  Sparkles, 
  Share2, 
  Copy, 
  Check, 
  MessageCircle, 
  Plus, 
  Trophy, 
  Users, 
  Flame, 
  ExternalLink,
  ChevronRight,
  TrendingUp,
  Award,
  BookOpen,
  CheckCircle2,
  Clock,
  Calendar,
  Lock,
  Unlock,
  Mail,
  Phone,
  MapPin,
  School,
  Target,
  Coins,
  Zap,
  Activity,
  HelpCircle,
  Video,
  Headphones,
  FileText
} from "lucide-react";
import { getPeople, updateUserRole, getAdminCatalog } from "@/lib/admin.functions";
import { getUserDetail } from "@/lib/profile.functions";
import { 
  listAdminChallengesFn, 
  createChallengeFn, 
  autoGenerateDailyChallengeFn, 
  getChallengeLeadsFn 
} from "@/lib/challenges.functions";
import { useAuth } from "@/hooks/use-auth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  Dialog, 
  DialogContent, 
  DialogDescription, 
  DialogHeader, 
  DialogTitle, 
  DialogTrigger,
  DialogFooter
} from "@/components/ui/dialog";
import { classLabel } from "@/lib/classes";
import { ViralTemplate } from "@/lib/viral-copy";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/admin")({
  head: () => ({
    meta: [
      { title: "Admin & Growth Hub — Easy Padhai" },
      { name: "description", content: "Manage Easy Padhai challenges, growth engine, learners, and roles." },
      { property: "og:title", content: "Admin & Growth Hub — Easy Padhai" },
      { property: "og:description", content: "Manage viral challenges, leads CRM, and user roles." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "robots", content: "noindex" },
    ],
  }),
  component: AdminPage,
});

const ROLES = ["student", "teacher", "admin"] as const;

function AdminPage() {
  const { user, isAdmin, loading } = useAuth();
  const navigate = useNavigate();
  const qc = useQueryClient();

  // Server functions
  const fetchPeople = useServerFn(getPeople);
  const setRole = useServerFn(updateUserRole);
  const fetchChallenges = useServerFn(listAdminChallengesFn);
  const fetchLeads = useServerFn(getChallengeLeadsFn);
  const autoGenChallenge = useServerFn(autoGenerateDailyChallengeFn);
  const createChallenge = useServerFn(createChallengeFn);
  const fetchCatalog = useServerFn(getAdminCatalog);

  // States
  const [openId, setOpenId] = useState<string | null>(null);
  const [selectedChallengeShare, setSelectedChallengeShare] = useState<any | null>(null);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [autoGenBusy, setAutoGenBusy] = useState(false);
  const [createBusy, setCreateBusy] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Custom Challenge Form State
  const [formChapterId, setFormChapterId] = useState("");
  const [formTitle, setFormTitle] = useState("");
  const [formCode, setFormCode] = useState("");
  const [formQuestionCount, setFormQuestionCount] = useState(5);

  useEffect(() => {
    if (!loading && !user) navigate({ to: "/auth", replace: true });
  }, [loading, user, navigate]);

  // Queries
  const { data: people, isLoading: peopleLoading } = useQuery({
    queryKey: ["people"],
    queryFn: () => fetchPeople(),
    enabled: Boolean(user) && isAdmin,
  });

  const { data: challenges, isLoading: challengesLoading } = useQuery({
    queryKey: ["admin-challenges"],
    queryFn: () => fetchChallenges(),
    enabled: Boolean(user) && isAdmin,
  });

  const { data: leads, isLoading: leadsLoading } = useQuery({
    queryKey: ["challenge-leads"],
    queryFn: () => fetchLeads(),
    enabled: Boolean(user) && isAdmin,
  });

  const { data: catalog } = useQuery({
    queryKey: ["admin-catalog"],
    queryFn: () => fetchCatalog(),
    enabled: Boolean(user) && isAdmin && createDialogOpen,
  });

  if (loading) return <Shell>Loading…</Shell>;
  if (user && !isAdmin) return <Shell>Admin access required.</Shell>;

  async function changeRole(userId: string, role: (typeof ROLES)[number]) {
    try {
      await setRole({ data: { userId, role } });
      await qc.invalidateQueries({ queryKey: ["people"] });
      toast.success("Role updated");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Could not update role");
    }
  }

  async function handleAutoGenerate() {
    setAutoGenBusy(true);
    try {
      const res = await autoGenChallenge();
      await qc.invalidateQueries({ queryKey: ["admin-challenges"] });
      toast.success(`Generated Daily Challenge: ${res.title}!`);
      // Open share dialog immediately
      setSelectedChallengeShare({
        ...res,
        templates: res.templates,
      });
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to auto-generate challenge");
    } finally {
      setAutoGenBusy(false);
    }
  }

  async function handleCreateCustomChallenge(e: React.FormEvent) {
    e.preventDefault();
    if (!formChapterId) {
      toast.error("Please select a chapter");
      return;
    }
    setCreateBusy(true);
    try {
      const res = await createChallenge({
        data: {
          chapterId: formChapterId,
          title: formTitle.trim() || undefined,
          code: formCode.trim() || undefined,
          questionCount: Number(formQuestionCount) || 5,
        },
      });
      await qc.invalidateQueries({ queryKey: ["admin-challenges"] });
      toast.success(`Challenge created: ${res.title}!`);
      setCreateDialogOpen(false);
      // Reset form
      setFormChapterId("");
      setFormTitle("");
      setFormCode("");
      // Open share dialog
      setSelectedChallengeShare({
        ...res,
        templates: res.templates,
      });
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to create challenge");
    } finally {
      setCreateBusy(false);
    }
  }

  function handleCopyText(text: string, id: string) {
    void navigator.clipboard.writeText(text);
    setCopiedId(id);
    toast.success("Copied to clipboard! Ready to paste on WhatsApp.");
    setTimeout(() => setCopiedId(null), 2500);
  }

  const totalPlays = (challenges || []).reduce((sum, c) => sum + (c.playsCount || 0), 0);
  const totalLeads = leads?.length || 0;

  return (
    <div className="mx-auto w-full max-w-5xl px-4 py-8 space-y-8">
      {/* Top Header */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="font-display text-3xl font-bold tracking-tight">Admin & Growth Hub</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Auto-generate viral micro-quizzes, track student leads, and manage roles.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button asChild variant="outline" size="sm" className="rounded-full">
            <Link to="/teach">Open Studio</Link>
          </Button>
        </div>
      </div>

      {/* Main Tabs */}
      <Tabs defaultValue="growth" className="w-full">
        <TabsList className="grid w-full grid-cols-2 rounded-2xl bg-secondary/80 p-1">
          <TabsTrigger value="growth" className="rounded-xl text-sm font-semibold">
            ⚡ Challenges & Growth Engine
          </TabsTrigger>
          <TabsTrigger value="people" className="rounded-xl text-sm font-semibold">
            👥 Learners & Roles ({people?.length ?? 0})
          </TabsTrigger>
        </TabsList>

        {/* =========================================================
            TAB 1: CHALLENGES & GROWTH ENGINE
        ========================================================= */}
        <TabsContent value="growth" className="space-y-6 pt-4">
          {/* Quick Metrics Bar */}
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            <Card className="rounded-2xl p-4 shadow-sm">
              <p className="text-xs font-semibold text-muted-foreground uppercase">Challenges</p>
              <p className="mt-1 text-2xl font-extrabold text-foreground">{challenges?.length || 0}</p>
            </Card>
            <Card className="rounded-2xl p-4 shadow-sm">
              <p className="text-xs font-semibold text-muted-foreground uppercase">Total Plays</p>
              <p className="mt-1 text-2xl font-extrabold text-primary">{totalPlays}</p>
            </Card>
            <Card className="rounded-2xl p-4 shadow-sm">
              <p className="text-xs font-semibold text-muted-foreground uppercase">Student Leads</p>
              <p className="mt-1 text-2xl font-extrabold text-emerald-600 dark:text-emerald-400">{totalLeads}</p>
            </Card>
            <Card className="rounded-2xl p-4 shadow-sm">
              <p className="text-xs font-semibold text-muted-foreground uppercase">Question Bank</p>
              <p className="mt-1 text-2xl font-extrabold text-amber-500">760+ MCQs</p>
            </Card>
          </div>

          {/* Action Header: Generate & Create */}
          <Card className="rounded-3xl border-primary/20 bg-gradient-to-r from-primary/10 via-background to-secondary/30 shadow-md">
            <CardContent className="flex flex-wrap items-center justify-between gap-4 p-6">
              <div className="space-y-1">
                <h2 className="font-display text-lg font-bold">Launch a 2-Minute Challenge</h2>
                <p className="text-xs text-muted-foreground max-w-lg">
                  Generate bite-sized challenges with zero signup friction. Students enter their WhatsApp number to play, and you get qualified student leads!
                </p>
              </div>

              <div className="flex flex-wrap items-center gap-2">
                <Button
                  onClick={handleAutoGenerate}
                  disabled={autoGenBusy}
                  className="rounded-full shadow-sm"
                >
                  <Sparkles className="mr-1.5 h-4 w-4" />
                  {autoGenBusy ? "Generating…" : "⚡ 1-Click Daily Challenge"}
                </Button>

                <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
                  <DialogTrigger asChild>
                    <Button variant="outline" className="rounded-full">
                      <Plus className="mr-1.5 h-4 w-4" />
                      Custom Challenge
                    </Button>
                  </DialogTrigger>
                  <DialogContent className="rounded-3xl max-w-md">
                    <DialogHeader>
                      <DialogTitle>Create Custom Micro-Challenge</DialogTitle>
                      <DialogDescription>
                        Pick any chapter from Class 9 to 12. Questions will be picked automatically from the bank.
                      </DialogDescription>
                    </DialogHeader>

                    <form onSubmit={handleCreateCustomChallenge} className="space-y-4 pt-2">
                      <div className="space-y-1.5">
                        <label className="text-xs font-semibold text-muted-foreground uppercase">
                          Select Chapter *
                        </label>
                        <select
                          required
                          value={formChapterId}
                          onChange={(e) => setFormChapterId(e.target.value)}
                          className="w-full rounded-xl border border-input bg-background px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-primary"
                        >
                          <option value="">-- Choose Chapter --</option>
                          {(catalog?.chapters || []).map((ch) => {
                            const sub = catalog?.subjects?.find((s) => s.id === ch.subject_id);
                            return (
                              <option key={ch.id} value={ch.id}>
                                {sub ? `Class ${sub.class_level} · ${sub.name}: ` : ""}{ch.title}
                              </option>
                            );
                          })}
                        </select>
                      </div>

                      <div className="space-y-1.5">
                        <label className="text-xs font-semibold text-muted-foreground uppercase">
                          Challenge Title (Optional)
                        </label>
                        <Input
                          placeholder="e.g. Current Electricity 2-Minute Brain Blitz"
                          value={formTitle}
                          onChange={(e) => setFormTitle(e.target.value)}
                          className="rounded-xl"
                        />
                      </div>

                      <div className="grid grid-cols-2 gap-3">
                        <div className="space-y-1.5">
                          <label className="text-xs font-semibold text-muted-foreground uppercase">
                            Short Code (Optional)
                          </label>
                          <Input
                            placeholder="e.g. elec-01"
                            value={formCode}
                            onChange={(e) => setFormCode(e.target.value.toLowerCase().replace(/[^a-z0-9_-]/g, ""))}
                            className="rounded-xl"
                          />
                        </div>
                        <div className="space-y-1.5">
                          <label className="text-xs font-semibold text-muted-foreground uppercase">
                            Questions Count
                          </label>
                          <Input
                            type="number"
                            min={3}
                            max={15}
                            value={formQuestionCount}
                            onChange={(e) => setFormQuestionCount(Number(e.target.value))}
                            className="rounded-xl"
                          />
                        </div>
                      </div>

                      <DialogFooter className="pt-2">
                        <Button
                          type="submit"
                          disabled={createBusy || !formChapterId}
                          className="w-full rounded-2xl py-5 font-semibold"
                        >
                          {createBusy ? "Creating…" : "Publish Challenge & Generate Copy 🚀"}
                        </Button>
                      </DialogFooter>
                    </form>
                  </DialogContent>
                </Dialog>
              </div>
            </CardContent>
          </Card>

          {/* Active Challenges List */}
          <Card className="rounded-3xl shadow-sm">
            <CardHeader className="pb-3">
              <CardTitle className="font-display text-lg">Active Challenges</CardTitle>
              <CardDescription>
                Live links ready to be shared on WhatsApp Status, Groups, and Instagram.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              {challengesLoading && <p className="text-sm text-muted-foreground">Loading challenges…</p>}
              {challenges?.length === 0 && (
                <div className="rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground">
                  No challenges created yet. Click "⚡ 1-Click Daily Challenge" above to launch your first one!
                </div>
              )}

              {(challenges || []).map((ch) => {
                const challengeUrl = `https://ep.studytube.co.in/c/${ch.code}`;
                return (
                  <div
                    key={ch.id}
                    className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-secondary/50 p-4 transition-all hover:bg-secondary/80"
                  >
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <Badge variant="outline" className="rounded-full text-xs font-bold text-primary">
                          /c/{ch.code}
                        </Badge>
                        <Badge variant="secondary" className="rounded-full text-xs">
                          Class {ch.classLevel} · {ch.subjectName}
                        </Badge>
                      </div>
                      <p className="font-semibold text-foreground">{ch.title}</p>
                      <p className="text-xs text-muted-foreground">
                        {ch.chapterTitle} · Created {new Date(ch.createdAt).toLocaleDateString()}
                      </p>
                    </div>

                    <div className="flex flex-wrap items-center gap-3">
                      <div className="text-right text-xs">
                        <p className="font-bold text-foreground">{ch.playsCount} Plays</p>
                        <p className="text-muted-foreground">Avg: {ch.avgScore}/5</p>
                      </div>

                      <Button
                        size="sm"
                        variant="outline"
                        className="rounded-full text-xs"
                        onClick={() => handleCopyText(challengeUrl, `url-${ch.id}`)}
                      >
                        {copiedId === `url-${ch.id}` ? (
                          <Check className="mr-1 h-3.5 w-3.5 text-emerald-500" />
                        ) : (
                          <Copy className="mr-1 h-3.5 w-3.5" />
                        )}
                        Copy Link
                      </Button>

                      <Button
                        size="sm"
                        className="rounded-full text-xs bg-[#25D366] hover:bg-[#20ba59] text-white shadow-sm"
                        onClick={() => setSelectedChallengeShare(ch)}
                      >
                        <Share2 className="mr-1.5 h-3.5 w-3.5" />
                        WhatsApp Copy & Share
                      </Button>

                      <Button asChild size="sm" variant="ghost" className="rounded-full p-2">
                        <a href={`/c/${ch.code}`} target="_blank" rel="noreferrer">
                          <ExternalLink className="h-4 w-4 text-muted-foreground" />
                        </a>
                      </Button>
                    </div>
                  </div>
                );
              })}
            </CardContent>
          </Card>

          {/* Student Leads CRM Section */}
          <Card className="rounded-3xl shadow-sm">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="font-display text-lg">Student Leads CRM</CardTitle>
                  <CardDescription>
                    Students who took the 2-minute challenges. One-click direct WhatsApp follow-up.
                  </CardDescription>
                </div>
                <Badge variant="secondary" className="rounded-full px-3 py-1 text-xs font-semibold">
                  {totalLeads} Captured Leads
                </Badge>
              </div>
            </CardHeader>
            <CardContent>
              {leadsLoading && <p className="text-sm text-muted-foreground">Loading student leads…</p>}
              {leads?.length === 0 && (
                <div className="rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground">
                  No leads captured yet. Share your challenge links to start getting student numbers!
                </div>
              )}

              {leads && leads.length > 0 && (
                <div className="divide-y divide-border/60 overflow-hidden rounded-2xl border">
                  <div className="grid grid-cols-12 bg-secondary/80 p-3 text-xs font-semibold text-muted-foreground">
                    <div className="col-span-4 sm:col-span-3">Student Name</div>
                    <div className="col-span-4 sm:col-span-3">WhatsApp Number</div>
                    <div className="col-span-4 sm:col-span-3">Challenge & Score</div>
                    <div className="hidden sm:col-span-3 sm:block text-right">Action</div>
                  </div>

                  {leads.map((lead) => {
                    const cleanPhone = lead.phone.replace(/[^0-9]/g, "").slice(-10);
                    const waChatUrl = `https://wa.me/91${cleanPhone}?text=${encodeURIComponent(
                      `Hello ${lead.studentName}! 👋\n\nI noticed you scored ${lead.score}/${lead.total} on the '${lead.challengeTitle}' challenge on Easy Padhai! ⚡\n\nDid you like the quick questions? We have complete audio lectures and free revision notes on this chapter here:\nhttps://ep.studytube.co.in/learn`,
                    )}`;

                    return (
                      <div
                        key={lead.id}
                        className="grid grid-cols-12 items-center p-3 text-sm transition-colors hover:bg-secondary/40"
                      >
                        <div className="col-span-4 sm:col-span-3 font-medium text-foreground">
                          {lead.studentName}
                        </div>
                        <div className="col-span-4 sm:col-span-3 font-mono text-xs text-muted-foreground">
                          +91 {lead.phone}
                        </div>
                        <div className="col-span-4 sm:col-span-3">
                          <Badge
                            variant="outline"
                            className={lead.score >= lead.total * 0.6 ? "text-emerald-600 border-emerald-500/40" : "text-amber-600 border-amber-500/40"}
                          >
                            {lead.score} / {lead.total} Correct
                          </Badge>
                          <p className="mt-0.5 text-[11px] text-muted-foreground truncate">
                            {lead.challengeTitle}
                          </p>
                        </div>
                        <div className="hidden sm:col-span-3 sm:flex justify-end gap-2">
                          <Button
                            asChild
                            size="sm"
                            className="rounded-full h-8 text-xs bg-[#25D366] hover:bg-[#20ba59] text-white"
                          >
                            <a href={waChatUrl} target="_blank" rel="noreferrer">
                              <MessageCircle className="mr-1 h-3.5 w-3.5" />
                              Chat on WhatsApp
                            </a>
                          </Button>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* =========================================================
            TAB 2: LEARNERS & ROLES
        ========================================================= */}
        <TabsContent value="people" className="space-y-4 pt-4">
          <Card className="rounded-3xl shadow-sm">
            <CardHeader className="pb-2">
              <CardTitle className="font-display text-lg">Registered Learners & Staff</CardTitle>
              <CardDescription>{people?.length ?? 0} registered users</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              {peopleLoading && <p className="text-sm text-muted-foreground">Loading…</p>}
              {(people ?? []).map((p) => (
                <div key={p.id} className="rounded-2xl bg-secondary px-4 py-3">
                  <div className="flex flex-wrap items-center justify-between gap-3">
                    <button
                      type="button"
                      className="text-left"
                      onClick={() => setOpenId((prev) => (prev === p.id ? null : p.id))}
                    >
                      <p className="font-medium underline-offset-4 hover:underline">
                        {p.full_name ?? "Learner"}
                      </p>
                      <p className="text-xs text-muted-foreground">
                        {classLabel(p.class_level)} · {p.total_xp ?? 0} XP
                      </p>
                    </button>
                    <div className="flex flex-wrap items-center gap-2">
                      {p.roles.map((r) => (
                        <Badge key={r} className="rounded-full text-xs">
                          {r}
                        </Badge>
                      ))}
                      {ROLES.map((r) => (
                        <Button
                          key={r}
                          size="sm"
                          variant="outline"
                          className="rounded-full text-xs"
                          disabled={p.roles.includes(r)}
                          onClick={() => changeRole(p.id, r)}
                        >
                          Make {r}
                        </Button>
                      ))}
                      <Button
                        size="sm"
                        variant="secondary"
                        className="rounded-full text-xs"
                        onClick={() => setOpenId((prev) => (prev === p.id ? null : p.id))}
                      >
                        {openId === p.id ? "Hide details" : "View details"}
                      </Button>
                    </div>
                  </div>

                  {openId === p.id && <UserDetail userId={p.id} />}
                </div>
              ))}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* =========================================================
          VIRAL WHATSAPP COPY MODAL / DRAWER
      ========================================================= */}
      {selectedChallengeShare && (
        <Dialog open={Boolean(selectedChallengeShare)} onOpenChange={() => setSelectedChallengeShare(null)}>
          <DialogContent className="rounded-3xl max-w-xl max-h-[85vh] overflow-y-auto">
            <DialogHeader>
              <div className="flex items-center gap-2">
                <Badge variant="outline" className="rounded-full text-xs font-bold text-primary">
                  /c/{selectedChallengeShare.code}
                </Badge>
                <Badge variant="secondary" className="rounded-full text-xs">
                  Ready to Share
                </Badge>
              </div>
              <DialogTitle className="text-lg font-bold">
                {selectedChallengeShare.title}
              </DialogTitle>
              <DialogDescription>
                Choose from 3 proven viral copywriting formulas. Click to copy and paste directly into WhatsApp Status or Groups!
              </DialogDescription>
            </DialogHeader>

            <div className="space-y-4 pt-2">
              {(selectedChallengeShare.templates as ViralTemplate[] || []).map((tpl) => (
                <div key={tpl.id} className="rounded-2xl border bg-secondary/40 p-4 space-y-2.5">
                  <div className="flex items-center justify-between">
                    <p className="text-xs font-bold text-primary uppercase tracking-wide">
                      {tpl.name}
                    </p>
                    <div className="flex items-center gap-2">
                      <Button
                        size="sm"
                        variant="outline"
                        className="h-8 rounded-full text-xs"
                        onClick={() => handleCopyText(tpl.text, tpl.id)}
                      >
                        {copiedId === tpl.id ? (
                          <Check className="mr-1 h-3.5 w-3.5 text-emerald-500" />
                        ) : (
                          <Copy className="mr-1 h-3.5 w-3.5" />
                        )}
                        Copy Text
                      </Button>

                      <Button
                        asChild
                        size="sm"
                        className="h-8 rounded-full text-xs bg-[#25D366] hover:bg-[#20ba59] text-white"
                      >
                        <a
                          href={`https://wa.me/?text=${encodeURIComponent(tpl.text)}`}
                          target="_blank"
                          rel="noreferrer"
                        >
                          <Share2 className="mr-1 h-3.5 w-3.5" />
                          Share
                        </a>
                      </Button>
                    </div>
                  </div>

                  <pre className="whitespace-pre-wrap font-sans text-xs text-muted-foreground bg-background/80 rounded-xl p-3 border leading-relaxed">
                    {tpl.text}
                  </pre>
                </div>
              ))}
            </div>
          </DialogContent>
        </Dialog>
      )}
    </div>
  );
}

function UserDetail({ userId }: { userId: string }) {
  const fetchDetail = useServerFn(getUserDetail);
  const { data, isLoading, error } = useQuery({
    queryKey: ["user-detail", userId],
    queryFn: () => fetchDetail({ data: { userId } }),
  });

  const [activeTab, setActiveTab] = useState<"unlocks" | "completed" | "tests" | "wallet">("unlocks");

  if (isLoading) {
    return (
      <div className="mt-4 flex items-center justify-center p-8 rounded-2xl bg-background/60 border text-muted-foreground animate-pulse">
        <Sparkles className="size-4 mr-2 text-primary animate-spin" />
        <span className="text-xs font-semibold">Loading complete learner profile and history…</span>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="mt-4 p-4 rounded-2xl bg-destructive/10 border border-destructive/20 text-destructive text-xs">
        Could not load details for this user.
      </div>
    );
  }

  const p = data.profile;
  const phoneNumber = p.phone || data.authPhone;
  const cleanPhone = phoneNumber ? phoneNumber.replace(/[^0-9]/g, "").slice(-10) : "";
  const waUrl = cleanPhone ? `https://wa.me/91${cleanPhone}?text=Hello%20${encodeURIComponent(p.full_name || "Student")},%20this%20is%20Easy%20Padhai%20support!` : null;

  return (
    <div className="mt-4 space-y-4 rounded-3xl bg-background p-4 sm:p-6 border border-border/80 shadow-xs">
      {/* 1. PROFILE IDENTITY & CONTACT BAR */}
      <div className="rounded-2xl border border-border/60 bg-muted/20 p-4 space-y-3">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="space-y-0.5">
            <h4 className="font-display text-base font-bold text-foreground flex items-center gap-2">
              {p.full_name || "Learner"}
              {p.onboarding_completed ? (
                <Badge variant="outline" className="text-[10px] bg-emerald-500/10 text-emerald-600 border-emerald-500/30">
                  Onboarded ✓
                </Badge>
              ) : (
                <Badge variant="outline" className="text-[10px] text-muted-foreground">
                  Pending Onboarding
                </Badge>
              )}
            </h4>
            <p className="text-xs text-muted-foreground">
              Member since {new Date(p.created_at).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}
              {data.lastSignInAt && (
                <span> · Last active {new Date(data.lastSignInAt).toLocaleDateString("en-IN", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}</span>
              )}
            </p>
          </div>

          {waUrl && (
            <Button
              asChild
              size="sm"
              className="rounded-full h-8 text-xs bg-[#25D366] hover:bg-[#20ba59] text-white shadow-xs"
            >
              <a href={waUrl} target="_blank" rel="noreferrer">
                <MessageCircle className="mr-1.5 h-3.5 w-3.5" />
                WhatsApp Student
              </a>
            </Button>
          )}
        </div>

        {/* Contact & Academic Metadata Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2.5 pt-1 text-xs">
          <div className="flex items-center gap-2 text-muted-foreground bg-background/80 p-2 rounded-xl border border-border/40">
            <Mail className="size-3.5 text-primary shrink-0" />
            <span className="truncate text-foreground font-medium">{data.email || "No email"}</span>
          </div>
          <div className="flex items-center gap-2 text-muted-foreground bg-background/80 p-2 rounded-xl border border-border/40">
            <Phone className="size-3.5 text-emerald-500 shrink-0" />
            <span className="truncate text-foreground font-medium">{phoneNumber || "No phone"}</span>
          </div>
          <div className="flex items-center gap-2 text-muted-foreground bg-background/80 p-2 rounded-xl border border-border/40">
            <BookOpen className="size-3.5 text-blue-500 shrink-0" />
            <span className="truncate text-foreground font-medium">{classLabel(p.class_level)} · {p.board || "Board N/A"}</span>
          </div>
          <div className="flex items-center gap-2 text-muted-foreground bg-background/80 p-2 rounded-xl border border-border/40">
            <MapPin className="size-3.5 text-orange-500 shrink-0" />
            <span className="truncate text-foreground font-medium">{[p.city, p.state].filter(Boolean).join(", ") || "City N/A"}</span>
          </div>
          <div className="flex items-center gap-2 text-muted-foreground bg-background/80 p-2 rounded-xl border border-border/40">
            <School className="size-3.5 text-indigo-500 shrink-0" />
            <span className="truncate text-foreground font-medium">{p.school_name || "School not set"}</span>
          </div>
          <div className="flex items-center gap-2 text-muted-foreground bg-background/80 p-2 rounded-xl border border-border/40">
            <Target className="size-3.5 text-rose-500 shrink-0" />
            <span className="truncate text-foreground font-medium">{p.goal || "Goal: General"}</span>
          </div>
          <div className="flex items-center gap-2 text-muted-foreground bg-background/80 p-2 rounded-xl border border-border/40">
            <Award className="size-3.5 text-amber-500 shrink-0" />
            <span className="truncate text-foreground font-medium">Ref: {p.referral_code || "None"} ({data.referralsQualified} invited)</span>
          </div>
          <div className="flex items-center gap-2 text-muted-foreground bg-background/80 p-2 rounded-xl border border-border/40">
            <Zap className="size-3.5 text-violet-500 shrink-0" />
            <span className="truncate text-foreground font-medium">{data.badges?.length ?? 0} Badges earned</span>
          </div>
        </div>
      </div>

      {/* 2. CORE STATS CARDS */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2.5">
        <Stat label="Current Credits" value={p.credits ?? 0} sub={`${data.creditsSpent} spent`} />
        <Stat label="Total XP" value={p.total_xp ?? 0} sub="Learner rank" />
        <Stat 
          label="Study Streak" 
          value={`${data.streak?.current_streak ?? 0}d`} 
          sub={`Best: ${data.streak?.longest_streak ?? 0}d`} 
        />
        <Stat 
          label="Study Time" 
          value={`${data.studyTime?.totalMinutes ?? 0}m`} 
          sub={`${data.studyTime?.daysCount ?? 0} days active`} 
        />
        <Stat label="Completed" value={data.lessonsCompleted ?? 0} sub="Finished lectures" />
        <Stat label="Quizzes Taken" value={data.attempts?.length ?? 0} sub="MCQ attempts" />
      </div>

      {/* 3. DETAILED ACTIVITY TABS */}
      <div className="pt-2">
        <div className="flex items-center justify-between border-b border-border/60 pb-2 mb-3">
          <div className="flex items-center gap-1.5 sm:gap-2">
            <button
              type="button"
              onClick={() => setActiveTab("unlocks")}
              className={cn(
                "px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer flex items-center gap-1.5",
                activeTab === "unlocks"
                  ? "bg-amber-500/15 text-amber-700 dark:text-amber-300 font-bold border border-amber-500/30 shadow-2xs"
                  : "text-muted-foreground hover:bg-muted/50 hover:text-foreground"
              )}
            >
              <Unlock className="size-3.5" />
              <span>Unlocked Lectures ({data.unlocks?.length ?? 0})</span>
            </button>
            <button
              type="button"
              onClick={() => setActiveTab("completed")}
              className={cn(
                "px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer flex items-center gap-1.5",
                activeTab === "completed"
                  ? "bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 font-bold border border-emerald-500/30 shadow-2xs"
                  : "text-muted-foreground hover:bg-muted/50 hover:text-foreground"
              )}
            >
              <CheckCircle2 className="size-3.5" />
              <span>Completed ({data.recentLessons?.length ?? 0})</span>
            </button>
            <button
              type="button"
              onClick={() => setActiveTab("tests")}
              className={cn(
                "px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer flex items-center gap-1.5",
                activeTab === "tests"
                  ? "bg-blue-500/15 text-blue-700 dark:text-blue-300 font-bold border border-blue-500/30 shadow-2xs"
                  : "text-muted-foreground hover:bg-muted/50 hover:text-foreground"
              )}
            >
              <Sparkles className="size-3.5" />
              <span>Quizzes & Tests ({data.attempts?.length ?? 0})</span>
            </button>
            <button
              type="button"
              onClick={() => setActiveTab("wallet")}
              className={cn(
                "px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer flex items-center gap-1.5",
                activeTab === "wallet"
                  ? "bg-purple-500/15 text-purple-700 dark:text-purple-300 font-bold border border-purple-500/30 shadow-2xs"
                  : "text-muted-foreground hover:bg-muted/50 hover:text-foreground"
              )}
            >
              <Coins className="size-3.5" />
              <span>Wallet History ({data.creditEvents?.length ?? 0})</span>
            </button>
          </div>
        </div>

        {/* TAB CONTENT: UNLOCKED LECTURES */}
        {activeTab === "unlocks" && (
          <div className="space-y-2">
            {(data.unlocks ?? []).length === 0 ? (
              <div className="p-6 text-center rounded-2xl bg-muted/20 border border-dashed border-border/60 text-muted-foreground text-xs">
                No lectures unlocked with credits yet. (Note: Lecture 1 of every chapter is free and does not require unlock).
              </div>
            ) : (
              <div className="divide-y divide-border/40 rounded-2xl border bg-muted/10 overflow-hidden">
                {data.unlocks.map((u: any, idx: number) => (
                  <div key={idx} className="p-3 hover:bg-muted/30 transition-colors flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
                    <div className="space-y-0.5">
                      <div className="flex items-center gap-2">
                        <Badge variant="outline" className="text-[10px] py-0 px-1.5 capitalize text-primary font-semibold">
                          {u.kind || "lecture"}
                        </Badge>
                        <span className="font-semibold text-foreground text-sm">
                          {u.title}
                        </span>
                      </div>
                      <p className="text-[11px] text-muted-foreground">
                        {u.subjectName ? `${u.subjectName} (Class ${u.classLevel || p.class_level}) · ` : ""}
                        {u.chapterTitle || "Chapter"}
                      </p>
                    </div>

                    <div className="flex items-center justify-between sm:justify-end gap-3 shrink-0">
                      <span className="font-bold text-amber-600 dark:text-amber-400">
                        −{u.cost ?? 10} Credits
                      </span>
                      <span className="text-muted-foreground text-[11px]">
                        {new Date(u.createdAt).toLocaleDateString("en-IN", {
                          day: "numeric",
                          month: "short",
                          year: "numeric",
                          hour: "2-digit",
                          minute: "2-digit",
                        })}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* TAB CONTENT: COMPLETED LESSONS */}
        {activeTab === "completed" && (
          <div className="space-y-2">
            {(data.recentLessons ?? []).length === 0 ? (
              <div className="p-6 text-center rounded-2xl bg-muted/20 border border-dashed border-border/60 text-muted-foreground text-xs">
                No completed lectures recorded yet.
              </div>
            ) : (
              <div className="divide-y divide-border/40 rounded-2xl border bg-muted/10 overflow-hidden">
                {data.recentLessons.map((l: any, idx: number) => (
                  <div key={idx} className="p-3 hover:bg-muted/30 transition-colors flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
                    <div className="space-y-0.5">
                      <div className="flex items-center gap-2">
                        <CheckCircle2 className="size-3.5 text-emerald-500 shrink-0" />
                        <span className="font-semibold text-foreground text-sm">
                          {l.title}
                        </span>
                      </div>
                      <p className="text-[11px] text-muted-foreground pl-5">
                        {l.subjectName ? `${l.subjectName} · ` : ""}{l.chapterTitle || "Chapter"}
                      </p>
                    </div>

                    <span className="text-muted-foreground text-[11px] shrink-0 pl-5 sm:pl-0">
                      Completed {new Date(l.completedAt).toLocaleDateString("en-IN", {
                        day: "numeric",
                        month: "short",
                        year: "numeric",
                        hour: "2-digit",
                        minute: "2-digit",
                      })}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* TAB CONTENT: QUIZZES & TESTS */}
        {activeTab === "tests" && (
          <div className="space-y-2">
            {(data.attempts ?? []).length === 0 ? (
              <div className="p-6 text-center rounded-2xl bg-muted/20 border border-dashed border-border/60 text-muted-foreground text-xs">
                No quiz or test attempts recorded yet.
              </div>
            ) : (
              <div className="divide-y divide-border/40 rounded-2xl border bg-muted/10 overflow-hidden">
                {data.attempts.map((a: any, idx: number) => (
                  <div key={idx} className="p-3 hover:bg-muted/30 transition-colors flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
                    <div className="space-y-0.5">
                      <div className="flex items-center gap-2">
                        <span className="font-semibold text-foreground text-sm">
                          {a.title}
                        </span>
                        <Badge
                          variant="outline"
                          className={cn(
                            "text-[10px] py-0 px-1.5 font-bold",
                            a.passed
                              ? "bg-emerald-500/10 text-emerald-600 border-emerald-500/30"
                              : "bg-rose-500/10 text-rose-600 border-rose-500/30"
                          )}
                        >
                          {a.passed ? "Passed" : "Needs Review"}
                        </Badge>
                      </div>
                      <p className="text-[11px] text-muted-foreground">
                        {a.subjectName ? `${a.subjectName} · ` : ""}{a.chapterTitle || "Chapter"}
                      </p>
                    </div>

                    <div className="flex items-center justify-between sm:justify-end gap-3 shrink-0">
                      <div className="text-right">
                        <span className="font-bold text-sm text-foreground">
                          {a.score} / {a.total}
                        </span>
                        <span className="text-[10px] text-muted-foreground ml-1">
                          ({a.percentage}%)
                        </span>
                      </div>
                      <span className="text-muted-foreground text-[11px]">
                        {new Date(a.createdAt).toLocaleDateString("en-IN", {
                          day: "numeric",
                          month: "short",
                          year: "numeric",
                          hour: "2-digit",
                          minute: "2-digit",
                        })}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* TAB CONTENT: WALLET TRANSACTIONS */}
        {activeTab === "wallet" && (
          <div className="space-y-2">
            {(data.creditEvents ?? []).length === 0 ? (
              <div className="p-6 text-center rounded-2xl bg-muted/20 border border-dashed border-border/60 text-muted-foreground text-xs">
                No credit/XP transactions recorded yet.
              </div>
            ) : (
              <div className="divide-y divide-border/40 rounded-2xl border bg-muted/10 overflow-hidden">
                {data.creditEvents.map((evt: any, idx: number) => {
                  const isPositive = evt.delta > 0;
                  return (
                    <div key={idx} className="p-3 hover:bg-muted/30 transition-colors flex items-center justify-between gap-2 text-xs">
                      <div className="flex items-center gap-2">
                        <span className={cn(
                          "size-6 rounded-full flex items-center justify-center font-bold text-xs shrink-0",
                          isPositive ? "bg-emerald-500/15 text-emerald-600" : "bg-amber-500/15 text-amber-600"
                        )}>
                          {isPositive ? "+" : "−"}
                        </span>
                        <span className="font-medium text-foreground">
                          {evt.reason || "Study Reward"}
                        </span>
                      </div>

                      <div className="flex items-center gap-3 shrink-0">
                        <span className={cn("font-bold text-xs", isPositive ? "text-emerald-600 dark:text-emerald-400" : "text-amber-600 dark:text-amber-400")}>
                          {isPositive ? `+${evt.delta}` : evt.delta} Credits
                        </span>
                        <span className="text-muted-foreground text-[11px]">
                          {new Date(evt.created_at).toLocaleDateString("en-IN", {
                            day: "numeric",
                            month: "short",
                            hour: "2-digit",
                            minute: "2-digit",
                          })}
                        </span>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

function Stat({ label, value, sub }: { label: string; value: string | number; sub?: string }) {
  return (
    <div className="rounded-2xl bg-secondary/70 p-3 text-center border border-border/40">
      <p className="text-[11px] font-semibold text-muted-foreground uppercase tracking-wider">{label}</p>
      <p className="mt-1 text-lg font-bold text-foreground">{value}</p>
      {sub && <p className="text-[10px] text-muted-foreground mt-0.5">{sub}</p>}
    </div>
  );
}

function Shell({ children }: { children: React.ReactNode }) {
  return <div className="mx-auto max-w-4xl px-4 py-16 text-center text-muted-foreground">{children}</div>;
}
